### ISSUE TITLE
Some item's values is 0

### ISSUE THREAD

**Issue by oeg91** [mxp190009/drop-simulator#2]
The issue is affecting the total value so is lower than it should be.
![image](https://user-images.githubusercontent.com/38496783/120127832-778a4800-c18e-11eb-95b4-9764d1db639c.png)
In this case the total profit only counts the adamant bars and not the scales. This seems to happend to some item not only zulrah's scales 

![image](https://user-images.githubusercontent.com/38496783/120127894-a86a7d00-c18e-11eb-8388-53ce81c5de7b.png)

**Comment by marshallez** [comment]
I will look into this.

Thanks

**Comment by unearthedjuan** [comment]
magic seeds from tob are 0 as well

**Comment by marshallez** [comment]
All item values come directly from the client itself, so I'm not sure if a RuneLite update broke the item values, or what is going on exactly. I'll try to have this fixed ( or at least the problem determined ) by the end of the week,

**Comment by marshallez** [comment]
The issue is that stackable items have different IDs depending upon how many are in the stack. For example, palm tree seeds:

- 1 seed has an id of 5289 and an image showing just one seed
- 2 seeds has an id of 5252 and an image showing two seeds
- 3 seeds has an id of 5253 and an image showing three seeds
- 4 seeds has an id of 5254 and an image showing four seeds
- 5+ seeds has an id of 5255 and an image showing five seeds

I use the OSRS box python package to acquire the ID of each item found in the boss tables. This table is returning the 2 seed ID on each seed, which is why each seed has an image of 2 seeds regardless of the actual number dropped. This is also why it only bugs out for seeds in boss tables. The RuneLite api doesn't seem to like the version of the seed ID being used for finding pricing. I'll work on a solution for this in the next few days.

**Comment by oeg91** [comment]
> The issue is that stackable items have different IDs depending upon how many are in the stack. For example, palm tree seeds:
> 
> * 1 seed has an id of 5289 and an image showing just one seed
> * 2 seeds has an id of 5252 and an image showing two seeds
> * 3 seeds has an id of 5253 and an image showing three seeds
> * 4 seeds has an id of 5254 and an image showing four seeds
> * 5+ seeds has an id of 5255 and an image showing five seeds
> 
> I use the OSRS box python package to acquire the ID of each item found in the boss tables. This table is returning the 2 seed ID on each seed, which is why each seed has an image of 2 seeds regardless of the actual number dropped. This is also why it only bugs out for seeds in boss tables. The RuneLite api doesn't seem to like the version of the seed ID being used for finding pricing. I'll work on a solution for this in the next few days.

Glad to know that you manage to find the soruce of the problem. Thanks for your work :)

**Comment by marshallez** [comment]
Turns out the reason the incorrect stackable item IDs were not working is because they were IDs of bank placeholders of the item rather than the ID of the item itself. All stackable items have been changed and now use the correct item ID. The values should show correctly now once the update merges with RuneLite.
